name: Build
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Set env variables
        run: |
          echo "TIMESTAMP=$(date +'%s')" >> $GITHUB_ENV
      - env:
          GITHUB_TOKEN: ${{ secrets.BOT_TOKEN }}
        run: |
          git checkout -b branch-$TIMESTAMP
          date > generated.txt
          git config user.name "yiannistr"
          git config user.email "yiannistr@users.noreply.github.com"
          git add .
          git commit -m "generated"
          git remote add bot https://${GITHUB_TOKEN}@github.com/yiannistr/test-gh-action.git
          git push bot HEAD:branch-$TIMESTAMP
